# Generated by Django 4.2.3 on 2023-11-21 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destinations',
            fields=[
                ('id_destination', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Nombre Destino')),
                ('mainImage', models.ImageField(blank=True, null=True, upload_to='destinations', verbose_name='Imagen Portada')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='destinations', verbose_name='Imagen 1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='destinations', verbose_name='Imagen 2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='destinations', verbose_name='Imagen 3')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='destinations', verbose_name='Imagen 4')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='destinations', verbose_name='Imagen 5')),
                ('distance', models.IntegerField(verbose_name='Distancia de Curacautín')),
                ('suitable_disabled', models.BooleanField(default=False, verbose_name='¿Apto para discapacitado?')),
                ('description', models.TextField(verbose_name='descripcion')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Destino',
                'verbose_name_plural': 'Destinos',
                'ordering': ['-created'],
            },
        ),
    ]
