# Generated by Django 4.2.3 on 2024-04-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinations',
            name='distance',
            field=models.IntegerField(verbose_name='Distancia de Curacautín (Kilometros)'),
        ),
    ]
