# Generated by Django 4.2.4 on 2023-11-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eats',
            fields=[
                ('id_eat', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Nombre restaurant')),
                ('mainImage', models.ImageField(blank=True, null=True, upload_to='restaurants', verbose_name='Imagen Portada')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='restaurants', verbose_name='Imagen 1')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='restaurants', verbose_name='Imagen 2')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='restaurants', verbose_name='Imagen 3')),
                ('address', models.CharField(max_length=50, verbose_name='Dirección')),
                ('description', models.TextField(verbose_name='descripcion')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
                'ordering': ['-created'],
            },
        ),
    ]
